apiVersion: v1
kind: Pod
metadata:
  name: kaniko-build
  namespace: default
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: 
      - --context=git://github.com/${GITHUB_USER}/openserverless-operator
      - --destination=docker-registry:5000/openserverless/operator:${TAG}
      - --insecure
      - --insecure-registry=docker-registry
