apiVersion: batch/v1
kind: Job
metadata:
  name: kaniko-build
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: kaniko
        image: gcr.io/kaniko-project/executor:latest
        args: 
          - --context=git://github.com/${GITHUB_USER}/openserverless-operator
          - --destination=docker-registry:5000/openserverless/operator:${TAG}
          - --insecure
          - --insecure-registry=docker-registry
      restartPolicy: Never