version: 3
vars:
 BASETAG: 0.1-dev
 TAG:
    sh: git describe --tags --abbrev=0 2>/dev/null || echo latest

dotenv: 
  - .env

tasks:

  tag: 
    silent: true
    cmds:
    - git tag -d $(git tag) 
    - git tag -f {{.BASETAG}}.$(date +%y%m%d%H%M)
    - env PAGER= git tag

  install-registry:
    cmds:
    - helm repo add twuni https://helm.twun.io
    - helm install docker-registry twuni/docker-registry --namespace default
    status:
    - kubectl -n default get po -l app=docker-registry

  tag-commit-push:
  - task tag
  - git commit -m "{{.TAG}}" -a
  - git push

  build:
    env:
      TAG: "{{.TAG}}"
    cmds:
    - test -n "$GITHUB_USER" || true "did you configure your .env?"
    - envsubst  <kaniko.yaml >_kaniko.yaml
    - cat _kaniko.yaml
    #- kubectl -n default create configmap dockerfile-configmap --from-file=Dockerfile
    #- kubectl apply -f kaniko.yaml