version: 3
vars:
 BASETAG: 0.1-dev
 TAG:
    sh: git describe --tags --abbrev=0 2>/dev/null || echo latest

dotenv: 
  - .env

tasks:

  default: task -l

  tag: 
    silent: true
    desc: generate a new tag based on the current time 
    cmds:
    - git tag -d $(git tag) 
    - git tag -f {{.BASETAG}}.$(date +%y%m%d%H%M)
    - env PAGER= git tag

  install-registry:
    desc: install a local registry
    cmds:
    - helm repo add twuni https://helm.twun.io
    - helm install docker-registry twuni/docker-registry --namespace default
    status:
    - kubectl -n default get po -l app=docker-registry

  tag-commit-push:
  - task: tag
  - git commit -m "{{.TAG}}" -a
  - git push

  kaniko-build:
    env:
      TAG: "{{.TAG}}"
    cmds:
    - test -n "$GITHUB_USER" || true "did you configure your .env?"
    - envsubst  <kaniko.yaml >_kaniko.yaml
    - cat _kaniko.yaml
    - kubectl -n default delete pod/kaniko || true
    - kubectl apply -f _kaniko.yaml

  build:
    - task: install-registry
    - task: tag-commit-push
    - task: kaniko-build