version: 3
vars:
 BASETAG: 0.1-dev
 TAG:
    sh: git describe --tags --abbrev=0 2>/dev/null || echo latest

dotenv: 
  - .env

tasks:

  default: task -l

  tag: 
    silent: true
    desc: generate a new tag based on the current time 
    cmds:
    - git tag -d $(git tag) 
    - git tag -f {{.BASETAG}}.$(date +%y%m%d%H%M)
    - env PAGER= git tag

  install-registry:
    desc: install a local registry
    cmds:
    - sudo cp registries.yaml /etc/rancher/k3s/registries.yaml
    - sudo systemctl restart k3s
    - helm repo add twuni https://helm.twun.io
    - >
      helm install docker-registry twuni/docker-registry 
      --namespace default 
      --set service.type=NodePort
      --set service.nodePort=30050
    status:
    - kubectl -n default get po -l app=docker-registry | grep docker-registry

  tag-commit-push:
    desc: tag, commit and push to your default upstream repo (see README.md)
    cmds:
    - task: tag
    - git commit -m "{{.TAG}}" -a
    - git push

  kaniko-build:
    desc: build in current kubernetes with Kaniko
    env:
      TAG: "{{.TAG}}"
    cmds:
    - test -n "$GITHUB_USER" || true "did you configure your .env?"
    - envsubst  <kaniko-build.yaml >_kaniko-build.yaml
    - kubectl -n default delete job/kaniko-build || true
    - kubectl apply -f _kaniko-build.yaml
    - kubectl wait po --for=condition=ready -l app=kaniko-build -n default 

  build-logs:
    desc: show logs of the latest build
    cmds:
    - kubectl -n default logs -l app=kaniko-build -f

  build:
    desc: build the operator image
    cmds: 
    - task: install-registry
    - task: tag-commit-push
    - task: kaniko-build
    - task: build-logs

  deploy:
    desc: deploy the current operator image
    env:
      TAG: "{{.TAG}}"
    cmds:
    - envsubst  <operator-deploy.yaml >_operator-deploy.yaml
    - kubectl apply -f _operator-deploy.yaml
